# 2. Numpy 배열

* Numpy에는 ndarray라는 데이터 타입의 배열이 생성된다.
* ndarray는 같은 타입의 데이터만 저장할 수 있다.
* Python의 list보다 계산 속도가 빠르다.


In [1]:
# import하기
import numpy as np

## 2-1. np.array() 함수로 생성하기
### 1차원 배열 생성하기

In [10]:
# 1차원 배열
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [11]:
# type 확인
type(arr)

numpy.ndarray

In [12]:
#array()에는 반드시 data가 1개 들어가야 한다!!
np.array(1,2,3,4)

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [13]:
#data type
arr.dtype

dtype('int64')

In [18]:
# overflow 테스트
arr = np.array([9223372036854775808,2,3,4])
arr

array([9.22337204e+18, 2.00000000e+00, 3.00000000e+00, 4.00000000e+00])

In [42]:
arr = np.array([1,2,3,4],dtype=float) #np.float64
arr

array([1., 2., 3., 4.])

In [43]:
arr.dtype

dtype('float64')

In [44]:
# shape : 각 차원의 배열의 size (모양)
arr.shape

(4,)

In [45]:
# size : 배열의 전체 element 수
arr.size

4

In [46]:
# ndim : 차원의 수
arr.ndim

1

In [47]:
arr = np.array([1,2,3,3.14])
arr

array([1.  , 2.  , 3.  , 3.14])

In [48]:
arr = np.array([1,2,3,3.14], dtype=int)
arr

array([1, 2, 3, 3])

In [49]:
# > : big-endian, < : little-endian
arr = np.array([1,3.14,'1234'])
arr

array(['1', '3.14', '1234'], dtype='<U32')

In [50]:
# 이미 있는 배열을 타입이 다른 다른 배열로 생성하기
new_arr = arr.astype(float)
new_arr

array([1.000e+00, 3.140e+00, 1.234e+03])

In [51]:
arr.dtype, new_arr.dtype

(dtype('<U32'), dtype('float64'))

In [4]:
arr = np.array([1,2,3,4])
arr2 = np.array([1,2,3,4])
new_arr = np.array([arr,arr2])
new_arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

## 2차원 배열 생성하기

In [6]:
arr2 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
arr2.dtype,arr2.shape,arr2.size, arr2.ndim

(dtype('int64'), (3, 4), 12, 2)

In [8]:
new_arr = arr2.astype(int)
new_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## 2-2. np.arange() 함수로 생성하기

In [10]:
#파이썬의 range
for i in range(0,10,2): #0, 9
    print(i)

0
2
4
6
8


# 1차원 배열 생성하기

In [14]:
# 1~10
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

# 2차원 배열 생성하기


In [44]:
# 0~11
arr = np.arange(0,12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [45]:
arr2 = arr.reshape((3,4))
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
arr,arr2

(array([0., 0., 0., 0.]),
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]))

In [46]:
# 원본 배열의 shape를 변경하고자 할 경우
arr.shape=(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## 2-3. np.zeros() 함수

In [40]:
# 1차원 배열
arr = np.zeros(4)
arr

array([0., 0., 0., 0.])

In [41]:
# 2차원 배열
arr2 = np.zeros((3,4))
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## 2-4. np.ones() 함수

In [36]:
# 1차원 배열
arr = np.ones(4)
arr

array([1., 1., 1., 1.])

In [37]:
# 2차원 배열
arr2 = np.ones((3,4))

### 2-5. np.linspace() 함수

In [52]:
arr = np.linspace(0,10,5)
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [53]:
arr = np.linspace(0,10)
arr

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [54]:
arr.shape

(50,)

In [55]:
arr2 = arr.reshape((10,5))
arr2

array([[ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653],
       [ 1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469],
       [ 2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286],
       [ 3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102],
       [ 4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918],
       [ 5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735],
       [ 6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551],
       [ 7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367],
       [ 8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184],
       [ 9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ]])

### 2-6. np.full() 함수

In [57]:
# 특정 값으로 배열을 생성할 경우
arr = np.full(4,10)
arr

array([10, 10, 10, 10])

In [58]:
arr2 = np.full((3,4),10)
arr2

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [59]:
arr2 = np.full

### 2-7. np.eye() 함수

In [61]:
# 단위 행렬 (항등 행렬)
arr = np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 2-8. np.random()을 이용

In [4]:
import numpy as np

In [5]:
np.random.rand(4)

array([0.19156915, 0.38391096, 0.55992757, 0.9963935 ])

In [6]:
arr2 = np.random.rand(3,4)
arr2

array([[0.41494467, 0.68070758, 0.34541725, 0.54204252],
       [0.462441  , 0.98909019, 0.83012516, 0.42470233],
       [0.37157647, 0.77544115, 0.54915103, 0.78503744]])

In [8]:
arr = np.random.randint(5,size=10)
arr

array([0, 4, 3, 0, 4, 0, 4, 4, 3, 3])

In [10]:
arr2 = np.random.randint(1,5,size=(3,4))
arr2

array([[3, 2, 1, 3],
       [2, 1, 2, 3],
       [4, 1, 4, 1]])

In [12]:
# 일정한 랜덤값을 만드려면?
np.random.seed(123)
np.random.rand(3, 4)


array([[0.69646919, 0.28613933, 0.22685145, 0.55131477],
       [0.71946897, 0.42310646, 0.9807642 , 0.68482974],
       [0.4809319 , 0.39211752, 0.34317802, 0.72904971]])

# 2-9. Numpy 배열 Save & Load

In [1]:
import numpy as np

In [3]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [4]:
np.save('my_arr',arr)

In [7]:
new_arr = np.load('my_arr.npy')
new_arr

array([0, 1, 2, 3, 4])