# 3. 연산

## 3-1. 산술연산

### 1차원 배열

In [1]:
import numpy as np

In [2]:
a = np.arange(1,5) #1~4
b = np.arange(5,9) #5~8
a,b

(array([1, 2, 3, 4]), array([5, 6, 7, 8]))

In [3]:
a.shape, b.shape

((4,), (4,))

In [4]:
#shape 이 같아야 함
a + b

array([ 6,  8, 10, 12])

In [5]:
a - b

array([-4, -4, -4, -4])

In [6]:
a * b

array([ 5, 12, 21, 32])

In [7]:
a / b

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

## 2차원 배열

In [8]:
a = np.arange(1, 7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
b = np.arange(7,13).reshape(2,3)
b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [10]:
a + b

array([[ 8, 10, 12],
       [14, 16, 18]])

In [11]:
a - b

array([[-6, -6, -6],
       [-6, -6, -6]])

In [12]:
# 단순 곱셈(이렇게는 안쓰임)
a * b

array([[ 7, 16, 27],
       [40, 55, 72]])

In [13]:
a / b

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

### 행렬의 곱셉 (dot product)

In [14]:
# 중요
b = np.arange(1,7).reshape(3,2)
a,b


(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2],
        [3, 4],
        [5, 6]]))

In [15]:
np.dot(a,b)

array([[22, 28],
       [49, 64]])

In [16]:
a.dot(b)

array([[22, 28],
       [49, 64]])

In [17]:
# 비교
a < 4

array([[ True,  True,  True],
       [False, False, False]])

### 배열과 숫자(Scalar)와의 연산 (Broadcasting)

In [18]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [19]:
a + 3

array([4, 5, 6])

In [20]:
a - 3

array([-2, -1,  0])

In [21]:
a * 3

array([3, 6, 9])

In [22]:
a / 3

array([0.33333333, 0.66666667, 1.        ])

## 3-2. Aggregation 함수

## 1차원 배열

In [23]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [24]:
# max값 찾기
np.max(a)

5

In [25]:
a.max()

5

In [26]:
# min값 찾기
np.min(a)

1

In [27]:
a.min()

1

In [28]:
# 배열요소의 합 구하기
np.sum(a)

15

In [29]:
# 평균구하기 (average)
np.mean(a)

3.0

In [30]:
# 이상치(OutLier)가 있는 경우에는 mean값이 배열을 대표할 수 없음
a = np.array([1,2,3,4,100])
np.mean(a)

22.0

In [31]:
# 중앙값(중위값) (순서 섞여있어도 ㄱㅊ)
np.median(a)

3.0

In [32]:
# 데이터의 개수가 짝수인 경우
a = np.array([1,2,3,100])
np.median(a)

2.5

In [33]:
# std : 표준편차 (standard deviation)
np.std(a)

42.44113570582201

## 2차원 배열

In [34]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
np.max(a)

6

In [36]:
np.min(a)

1

In [37]:
np.max(a,axis=0)

array([4, 5, 6])

In [38]:
np.max(a,axis=1)

array([3, 6])

In [39]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
np.sum(a)

21

In [41]:
np.sum(a,axis = 0)

array([5, 7, 9])

In [42]:
np.sum(a,axis = 1)

array([ 6, 15])

In [43]:
# cumsum
np.cumsum(a)

array([ 1,  3,  6, 10, 15, 21])

In [44]:
np.cumsum(a,axis=0)

array([[1, 2, 3],
       [5, 7, 9]])

In [45]:
np.cumsum(a,axis=1)

array([[ 1,  3,  6],
       [ 4,  9, 15]])

In [47]:
# corrcoef (상관계수)
# 두 변수 사이의 연관성을 나타내는 수치
# 키와 몸무게의 상관관계
h = [160, 165, 170, 180]
w = [47, 55, 70, 85]
np.corrcoef(h,w)

array([[1.        , 0.99040485],
       [0.99040485, 1.        ]])

In [48]:
ha = np.mean(h)
wa = np.mean(w)
ha, wa

(168.75, 64.25)

In [50]:
a = np.sqrt(np.sum((h - ha) ** 2))
a

14.79019945774904

In [51]:
b = np.sqrt(np.sum((w - wa) ** 2))
b

29.098969053902923

In [52]:
c = np.sum((h - ha) * (w - wa))
c

426.25

In [53]:
r = c / (a * b)
r

0.990404850180661