# 4. 정렬

## 4-1. 1차원 정렬

In [2]:
import numpy as np

In [3]:
np.random.seed(100)
arr = np.random.randint(1,10,size = 10) #1~9, 10개
arr

array([9, 9, 4, 8, 8, 1, 5, 3, 6, 3])

In [4]:
# 오름차순 정렬
np.sort(arr)

array([1, 3, 3, 4, 5, 6, 8, 8, 9, 9])

In [5]:
np.sort(arr)[::-1]

array([9, 9, 8, 8, 6, 5, 4, 3, 3, 1])

In [6]:
# 원본 배열이 바뀜
arr.sort() 

In [7]:
arr

array([1, 3, 3, 4, 5, 6, 8, 8, 9, 9])

## 4-2. 2차원 배열 

In [8]:
np.random.seed(100)
arr2 = np.random.randint(1,10,size = (3,4))
arr2

array([[9, 9, 4, 8],
       [8, 1, 5, 3],
       [6, 3, 3, 3]])

In [9]:
np.sort(arr2) # axis = 1과 동일

array([[4, 8, 9, 9],
       [1, 3, 5, 8],
       [3, 3, 3, 6]])

In [10]:
np.sort(arr2,axis=0)

array([[6, 1, 3, 3],
       [8, 3, 4, 3],
       [9, 9, 5, 8]])

In [11]:
# index를 리턴하는 정렬함수 : argsort
np.argsort(arr2) #axis =1 

array([[2, 3, 0, 1],
       [1, 3, 2, 0],
       [1, 2, 3, 0]])

In [12]:
np.argsort(arr2, axis = 0)

array([[2, 1, 2, 1],
       [1, 2, 0, 2],
       [0, 0, 1, 0]])