# 5. 인덱싱과 슬라이싱

## 5-1. 인덱싱

In [1]:
import numpy as np

In [2]:
# 1차원 배열
arr = np.arange(1,11) #1~10까지
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr[1], arr[4], arr[9]

(2, 5, 10)

In [4]:
# 2차원 배열
arr2 = np.arange(1,13).reshape(3,4) #1~12까지 3*4 2차원 배열
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
arr2[0,1], arr2[1,2], arr2[-1,-1]

(2, 7, 12)

In [6]:
arr2[0][1], arr2[1][2], arr2[-1][-1]

(2, 7, 12)

## 5-2. 슬라이싱

In [7]:
#1차원 배열
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
# 슬라이싱 [start:end:step]
arr[2:6]

array([3, 4, 5, 6])

In [9]:
# 3~끝까지
arr[2:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
# 처음~6까지
arr[:6]

array([1, 2, 3, 4, 5, 6])

In [11]:
# 처음~끝까지
arr[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
# 슬라이싱한 후 값을 변경하면 원본 배열에 영향을 미칠까?
new_arr = arr[2:6]
new_arr

array([3, 4, 5, 6])

In [13]:
new_arr[0] = 100
new_arr

array([100,   4,   5,   6])

In [14]:
arr # 원본이 바뀌어버림

array([  1,   2, 100,   4,   5,   6,   7,   8,   9,  10])

In [15]:
copy_arr = np.copy(arr)
copy_arr

array([  1,   2, 100,   4,   5,   6,   7,   8,   9,  10])

In [16]:
arr[::2]

array([  1, 100,   5,   7,   9])

In [17]:
# 2차원 배열
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
# 첫번째 행을 가져오기
arr2[0,:]

array([1, 2, 3, 4])

In [19]:
arr2[:,2]

array([ 3,  7, 11])

In [20]:
# 첫번째, 두번째 행을 가져오기
arr2[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [21]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
#두번째, 세번째 열을 가져오기
arr2[:, 1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [23]:
arr2[:2,1:3]

array([[2, 3],
       [6, 7]])

## 5-3. Fancy 인덱싱

In [24]:
# 1차원
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
# [3,6,8]로 된 1차원 배열 만들기
np.array([arr[2],arr[5],arr[7]])

array([3, 6, 8])

In [27]:
# Fancy 인덱싱
# 인덱스로 배열 만들기
arr[[2,5,7]]

array([3, 6, 8])

In [ ]:
#arr[2,5,7] = arr[2][5][7]

In [30]:
# 2차원 배열
arr2 = np.arange(1,13).reshape(3,4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [49]:
# 슬라이싱
arr2[:,1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [55]:
# Fancy 인덱싱
arr2[:,[1,2]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

## 5-4. Boolean 인덱싱

In [56]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [61]:
cond = [True,True,False,False,True]

In [62]:
# Boolean 인덱싱
arr[cond] #개수가 일치해야함

array([0, 1, 4])

In [63]:
arr

array([0, 1, 2, 3, 4])

In [65]:
arr > 2

array([False, False, False,  True,  True])

In [66]:
arr[arr > 2]

array([3, 4])

In [69]:
# 짝수뽑기
arr[arr%2==0]

array([0, 2, 4])

In [76]:
# 1보다 작거나 3보다 큰 수 (0,4)
(arr<1) | (arr>3)

array([ True, False, False, False,  True])

In [77]:
arr[(arr<1) | (arr>3)]

array([0, 4])

In [79]:
# 2 이상 3 이하인 수 (2,3)
(arr>=2)&(arr<=3)

array([False, False,  True,  True, False])

In [80]:
arr[(arr>=2)&(arr<=3)]

array([2, 3])