# 6. 실습

In [85]:
# numpy import하기
import numpy as np

## 6-1. NumPy 배열 생성

In [86]:
# np.array()로 1차원 배열 [1, 2, 3, 4, 5] 생성 후 출력하기
arr = np.array([1,2,3,4,5])

In [87]:
# 1차원 배열의 데이터타입, 모양, 배열 전체 element의 수, 차원의 수 출력하기
arr.dtype, arr.size, arr.ndim, arr.shape

(dtype('int64'), 5, 1, (5,))

In [88]:
# np.array()로 아래 2차원 배열 생성 후 출력하기
# [[10, 20, 30, 40],
#  [50, 60, 70, 80]]
arr2 = np.array([10,20,30,40,50,60,70,80]).reshape(2,4)
arr2

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [89]:
# np.arange()로 1차원 배열 [1, 2, 3, 4, 5] 생성 후 출력하기
arr3 = np.arange(1,6)
arr3

array([1, 2, 3, 4, 5])

In [90]:
# np.arange()로 아래 2차원 배열 생성 후 출력하기
# [[10, 20, 30, 40],
#  [50, 60, 70, 80]]
arr4 = np.arange(10,81,10).reshape(2,4)
arr4

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [91]:
# 주사위를 100번 던져서 나오는 숫자 배열 출력하기
np.random.randint(6,size=100)

array([0, 1, 0, 5, 4, 2, 0, 0, 2, 5, 2, 1, 0, 5, 2, 1, 5, 4, 2, 0, 3, 3,
       3, 5, 0, 5, 1, 4, 2, 3, 3, 4, 2, 4, 3, 1, 0, 4, 3, 4, 5, 2, 2, 4,
       2, 5, 4, 1, 2, 2, 0, 2, 2, 3, 5, 4, 2, 4, 3, 5, 1, 0, 0, 5, 1, 5,
       2, 4, 2, 3, 3, 1, 2, 3, 0, 1, 5, 5, 1, 5, 3, 0, 4, 2, 5, 4, 3, 4,
       4, 2, 0, 1, 0, 4, 5, 2, 5, 4, 4, 5])

In [92]:
# np.random을 사용하여 랜덤 실수값으로 이루어진 (3, 4) 2차원 배열 생성
np.random.rand(3,4)

array([[0.88001849, 0.27454204, 0.22458118, 0.81397318],
       [0.05820075, 0.73015342, 0.03267909, 0.59998723],
       [0.03054111, 0.85960489, 0.43977952, 0.56044466]])

## 6-2. 산술연산

In [93]:
# [1, 2, 3, 4, 5], [6, 7, 8, 9, 10] 1차원 배열 2개를 생성하고 출력하기
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
a,b

(array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]))

In [94]:
# 1차원 배열간 산술연산(덧셈, 뺄셈, 곱셈, 나눗셈) 하기
a+b, a-b, a*b, a/b

(array([ 7,  9, 11, 13, 15]),
 array([-5, -5, -5, -5, -5]),
 array([ 6, 14, 24, 36, 50]),
 array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ]))

In [95]:
# [[1, 2, 3, 4, 5]   [[11, 12, 13, 14, 15]
#  [6, 7, 8, 9, 10]], [16, 17, 18, 19, 20]] 2차원 배열 2개를 생성하고 출력하기
arr1 = np.arange(1,11).reshape(2,5)
arr2 = np.arange(11,21).reshape(2,5)
arr1, arr2

(array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]),
 array([[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]))

In [96]:
# 2차원 배열간 산술연산(덧셈, 뺄셈, 나눗셈) 하기
arr1+arr2,arr1-arr2,arr1/arr2

(array([[12, 14, 16, 18, 20],
        [22, 24, 26, 28, 30]]),
 array([[-10, -10, -10, -10, -10],
        [-10, -10, -10, -10, -10]]),
 array([[0.09090909, 0.16666667, 0.23076923, 0.28571429, 0.33333333],
        [0.375     , 0.41176471, 0.44444444, 0.47368421, 0.5       ]]))

In [97]:
# 두번째 배열의 shape을 (5, 2)로 만들고 출력하기
arr2 = arr2.reshape(5,2)
arr2

array([[11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [98]:
# 행렬곱셈(dot product) 연산하기

np.dot(arr1,arr2)

array([[245, 260],
       [620, 660]])

## 6-3. Aggregation 함수

In [99]:
# 1~10까지 이루어진 1차원 배열 생성하기
a=np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [100]:
# 최대값, 최소값 출력하기
np.max(a),np.min(a)

(10, 1)

In [101]:
# 배열요소의 합, 평균값 출력하기
np.sum(a),np.mean(a)

(55, 5.5)

In [102]:
# 중앙값(중위값), 표준편차 출력하기
np.median(a),np.std(a)

(5.5, 2.8722813232690143)

In [103]:
# 1~20까지 이루어진 2차원 배열 (4, 5) 생성하기
arr2 = np.arange(1,21).reshape(4,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [104]:
# 각 행의 max값, min값 출력하기
np.min(arr2,axis=1),np.max(arr2,axis=1)

(array([ 1,  6, 11, 16]), array([ 5, 10, 15, 20]))

In [105]:
# 각 열의 max값, min값 출력하기
np.min(arr2,axis=0),np.max(arr2,axis=0)

(array([1, 2, 3, 4, 5]), array([16, 17, 18, 19, 20]))

In [106]:
# 각 행의 sum값 출력하기
np.sum(arr2,axis=1)

array([15, 40, 65, 90])

In [107]:
# 각 열의 sum값 출력하기
np.sum(arr2,axis=0)

array([34, 38, 42, 46, 50])

## 6-4. 정렬

In [108]:
# 1~100까지 랜덤 정수값을 갖는 1차원 배열 (10, ) 생성하기
# seed값 100부여하기
np.random.seed(100)
arr = np.random.randint(1,100,size = 10)
arr

array([ 9, 25, 68, 88, 80, 49, 11, 95, 53, 99])

In [109]:
# 위 1차원 배열을 오름차순 정렬하기
np.sort(arr)

array([ 9, 11, 25, 49, 53, 68, 80, 88, 95, 99])

In [110]:
# 위 1차원 배열을 내림차순 정렬하기
np.sort(arr)[::-1]

array([99, 95, 88, 80, 68, 53, 49, 25, 11,  9])

In [111]:
# 랜덤 seed값 100부여하기
# 1~100까지 랜덤 정수값을 갖는 2차원 배열 (5, 10) 생성하기
np.random.seed(100)
arr = np.random.randint(1,100,size = 50).reshape(5,10)
arr

array([[ 9, 25, 68, 88, 80, 49, 11, 95, 53, 99],
       [54, 67, 99, 15, 35, 25, 16, 61, 59, 17],
       [10, 94, 87,  3, 28,  5, 32,  2, 14, 84],
       [ 5, 92, 60, 68,  8, 50, 48, 66, 62, 15],
       [56, 72, 81,  3, 95, 20, 99, 64, 54, 28]])

In [112]:
# 열 기준 정렬하기
np.sort(arr,axis=0)

array([[ 5, 25, 60,  3,  8,  5, 11,  2, 14, 15],
       [ 9, 67, 68,  3, 28, 20, 16, 61, 53, 17],
       [10, 72, 81, 15, 35, 25, 32, 64, 54, 28],
       [54, 92, 87, 68, 80, 49, 48, 66, 59, 84],
       [56, 94, 99, 88, 95, 50, 99, 95, 62, 99]])

In [113]:
# 행 기준 정렬하기
np.sort(arr,axis=1)

array([[ 9, 11, 25, 49, 53, 68, 80, 88, 95, 99],
       [15, 16, 17, 25, 35, 54, 59, 61, 67, 99],
       [ 2,  3,  5, 10, 14, 28, 32, 84, 87, 94],
       [ 5,  8, 15, 48, 50, 60, 62, 66, 68, 92],
       [ 3, 20, 28, 54, 56, 64, 72, 81, 95, 99]])

## 6-5. 인덱싱과 슬라이싱

In [114]:
# 0~14로 이루어진 2차원 배열 (3, 5) 생성하기
arr = np.arange(0,15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [115]:
# 위 배열에서 7을 인덱싱하기
arr[1,2]

7

In [116]:
# 위 배열에서 14를 인덱싱하기 (음수 인덱스 사용)
arr[2,4]

14

In [117]:
# 위 배열에서 배열 [6, 7]을 슬라이싱하기
arr[1,1:3]

array([6, 7])

In [118]:
# 위 배열에서 배열 [7, 12]을 슬라이싱하기
arr[1:,2]

array([ 7, 12])

In [119]:
# 위 배열에서 [[3, 4], [8, 9]]을 슬라이싱하기
arr[:2,3:5]

array([[3, 4],
       [8, 9]])

In [120]:
# 위 배열에서 3의 배수 찾기
arr[arr%3==0]

array([ 0,  3,  6,  9, 12])

In [121]:
# 위 배열에서 4로 나누면 1이 남는 수 찾기
arr[arr%4==1]

array([ 1,  5,  9, 13])

In [122]:
# 위 배열에서 3의 배수이면서 4로 나누면 1이 남는 수 찾기
arr[(arr%3==0) & (arr%4==1)]

array([9])