# 6. 실습

In [1]:
# numpy import하기
import numpy as np

## 6-1. NumPy 배열 생성

In [2]:
# np.array()로 1차원 배열 [1, 2, 3, 4, 5] 생성 후 출력하기
arr = np.array([1,2,3,4,5])

In [3]:
# 1차원 배열의 데이터타입, 모양, 배열 전체 element의 수, 차원의 수 출력하기
arr.dtype, arr.size, arr.ndim, arr.shape

(dtype('int64'), 5, 1, (5,))

In [4]:
# np.array()로 아래 2차원 배열 생성 후 출력하기
# [[10, 20, 30, 40],
#  [50, 60, 70, 80]]
arr2 = np.array([10,20,30,40,50,60,70,80]).reshape(2,4)
arr2

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [5]:
# np.arange()로 1차원 배열 [1, 2, 3, 4, 5] 생성 후 출력하기
arr3 = np.arange(1,6)
arr3

array([1, 2, 3, 4, 5])

In [6]:
# np.arange()로 아래 2차원 배열 생성 후 출력하기
# [[10, 20, 30, 40],
#  [50, 60, 70, 80]]
arr4 = np.arange(10,81,10).reshape(2,4)
arr4

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [7]:
# 주사위를 100번 던져서 나오는 숫자 배열 출력하기
np.random.randint(6,size=100)

array([4, 4, 3, 2, 4, 1, 1, 2, 1, 4, 1, 3, 1, 0, 0, 2, 3, 0, 2, 5, 0, 4,
       0, 3, 2, 0, 2, 4, 3, 1, 1, 0, 4, 4, 5, 2, 5, 1, 2, 1, 4, 4, 2, 1,
       5, 0, 4, 4, 3, 5, 2, 1, 4, 1, 1, 1, 0, 2, 5, 1, 5, 3, 2, 0, 0, 5,
       1, 4, 1, 5, 0, 4, 3, 5, 5, 5, 2, 0, 4, 1, 1, 3, 2, 2, 2, 4, 3, 1,
       0, 5, 3, 2, 4, 0, 4, 5, 5, 1, 5, 0])

In [40]:
np.random.randint(1,7,size=100)

array([1, 2, 1, 6, 5, 3, 1, 1, 3, 6, 3, 2, 1, 6, 3, 2, 6, 5, 3, 1, 4, 4,
       4, 6, 1, 6, 2, 5, 3, 4, 4, 5, 3, 5, 4, 2, 1, 5, 4, 5, 6, 3, 3, 5,
       3, 6, 5, 2, 3, 3, 1, 3, 3, 4, 6, 5, 3, 5, 4, 6, 2, 1, 1, 6, 2, 6,
       3, 5, 3, 4, 4, 2, 3, 4, 1, 2, 6, 6, 2, 6, 4, 1, 5, 3, 6, 5, 4, 5,
       5, 3, 1, 2, 1, 5, 6, 3, 6, 5, 5, 6])

In [12]:
# 2차원 배열간 산술연산(덧셈, 뺄셈, 나눗셈) 하기
arr1+arr2,arr1-arr2,arr1/arr2

(array([[12, 14, 16, 18, 20],
        [22, 24, 26, 28, 30]]),
 array([[-10, -10, -10, -10, -10],
        [-10, -10, -10, -10, -10]]),
 array([[0.09090909, 0.16666667, 0.23076923, 0.28571429, 0.33333333],
        [0.375     , 0.41176471, 0.44444444, 0.47368421, 0.5       ]]))

In [13]:
# 두번째 배열의 shape을 (5, 2)로 만들고 출력하기
arr2 = arr2.reshape(5,2)
arr2

array([[11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [14]:
# 행렬곱셈(dot product) 연산하기

np.dot(arr1,arr2)

array([[245, 260],
       [620, 660]])

## 6-3. Aggregation 함수

In [15]:
# 1~10까지 이루어진 1차원 배열 생성하기
a=np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
# 최대값, 최소값 출력하기
np.max(a),np.min(a)

(10, 1)

In [17]:
# 배열요소의 합, 평균값 출력하기
np.sum(a),np.mean(a)

(55, 5.5)

In [18]:
# 중앙값(중위값), 표준편차 출력하기
np.median(a),np.std(a)

(5.5, 2.8722813232690143)

In [19]:
# 1~20까지 이루어진 2차원 배열 (4, 5) 생성하기
arr2 = np.arange(1,21).reshape(4,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [20]:
# 각 행의 max값, min값 출력하기
np.min(arr2,axis=1),np.max(arr2,axis=1)

(array([ 1,  6, 11, 16]), array([ 5, 10, 15, 20]))

In [21]:
# 각 열의 max값, min값 출력하기
np.min(arr2,axis=0),np.max(arr2,axis=0)

(array([1, 2, 3, 4, 5]), array([16, 17, 18, 19, 20]))

In [22]:
# 각 행의 sum값 출력하기
np.sum(arr2,axis=1)

array([15, 40, 65, 90])

In [23]:
# 각 열의 sum값 출력하기
np.sum(arr2,axis=0)

array([34, 38, 42, 46, 50])

## 6-4. 정렬

In [24]:
# 1~100까지 랜덤 정수값을 갖는 1차원 배열 (10, ) 생성하기
# seed값 100부여하기
np.random.seed(100)
arr = np.random.randint(1,100,size = 10)
arr

array([ 9, 25, 68, 88, 80, 49, 11, 95, 53, 99])

In [25]:
# 위 1차원 배열을 오름차순 정렬하기
np.sort(arr)

array([ 9, 11, 25, 49, 53, 68, 80, 88, 95, 99])

In [26]:
# 위 1차원 배열을 내림차순 정렬하기
np.sort(arr)[::-1]

array([99, 95, 88, 80, 68, 53, 49, 25, 11,  9])

In [27]:
# 랜덤 seed값 100부여하기
# 1~100까지 랜덤 정수값을 갖는 2차원 배열 (5, 10) 생성하기
np.random.seed(100)
arr = np.random.randint(1,100,size = 50).reshape(5,10)
arr

array([[ 9, 25, 68, 88, 80, 49, 11, 95, 53, 99],
       [54, 67, 99, 15, 35, 25, 16, 61, 59, 17],
       [10, 94, 87,  3, 28,  5, 32,  2, 14, 84],
       [ 5, 92, 60, 68,  8, 50, 48, 66, 62, 15],
       [56, 72, 81,  3, 95, 20, 99, 64, 54, 28]])

In [28]:
# 열 기준 정렬하기
np.sort(arr,axis=0)

array([[ 5, 25, 60,  3,  8,  5, 11,  2, 14, 15],
       [ 9, 67, 68,  3, 28, 20, 16, 61, 53, 17],
       [10, 72, 81, 15, 35, 25, 32, 64, 54, 28],
       [54, 92, 87, 68, 80, 49, 48, 66, 59, 84],
       [56, 94, 99, 88, 95, 50, 99, 95, 62, 99]])

In [29]:
# 행 기준 정렬하기
np.sort(arr,axis=1)

array([[ 9, 11, 25, 49, 53, 68, 80, 88, 95, 99],
       [15, 16, 17, 25, 35, 54, 59, 61, 67, 99],
       [ 2,  3,  5, 10, 14, 28, 32, 84, 87, 94],
       [ 5,  8, 15, 48, 50, 60, 62, 66, 68, 92],
       [ 3, 20, 28, 54, 56, 64, 72, 81, 95, 99]])

## 6-5. 인덱싱과 슬라이싱

In [30]:
# 0~14로 이루어진 2차원 배열 (3, 5) 생성하기
arr = np.arange(0,15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [31]:
# 위 배열에서 7을 인덱싱하기
arr[1,2]

7

In [32]:
# 위 배열에서 14를 인덱싱하기 (음수 인덱스 사용)
arr[2,4]

14

In [33]:
# 위 배열에서 배열 [6, 7]을 슬라이싱하기
arr[1,1:3]

array([6, 7])

In [34]:
# 위 배열에서 배열 [7, 12]을 슬라이싱하기
arr[1:,2]

array([ 7, 12])

In [35]:
# 위 배열에서 [[3, 4], [8, 9]]을 슬라이싱하기
arr[:2,3:5]

array([[3, 4],
       [8, 9]])

In [36]:
# 위 배열에서 3의 배수 찾기
arr[arr%3==0]

array([ 0,  3,  6,  9, 12])

In [41]:
arr%3==0

array([[ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False]])

In [37]:
# 위 배열에서 4로 나누면 1이 남는 수 찾기
arr[arr%4==1]

array([ 1,  5,  9, 13])

In [38]:
# 위 배열에서 3의 배수이면서 4로 나누면 1이 남는 수 찾기
arr[(arr%3==0) & (arr%4==1)]

array([9])